# Generated by Django 6.0.4 on 2026-06-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariobombero',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
