# Generated by Django 6.0.4 on 2026-07-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_usuariobombero_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='disponibilidad',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible'), ('En Uso', 'En Uso')], default='Disponible', max_length=50),
        ),
    ]
