# Generated by Django 6.0.4 on 2026-07-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_herramienta_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariobombero',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Aprobado por Jefe'),
        ),
    ]
