# Generated by Django 6.0.4 on 2026-07-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_usuariobombero_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='disponibilidad',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En Stock', 'En Stock'), ('En Uso', 'En Uso'), ('No Disponible', 'No Disponible')], default='Disponible', max_length=50),
        ),
    ]
