# Generated by Django 6.0.4 on 2026-07-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_registroactividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='estado',
            field=models.CharField(choices=[('Funcional', 'Funcional'), ('En uso', 'En uso'), ('No funcional', 'No funcional')], default='Funcional', max_length=50),
        ),
    ]
