# Generated by Django 6.0.4 on 2026-08-06 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_eventocalendario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParteGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('turno', models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=10, verbose_name='Turno')),
                ('unidad', models.CharField(choices=[('estructural', 'Unidad Estructural'), ('rescate', 'Unidad de Rescate'), ('forestal', 'Unidad Forestal'), ('cisterna', 'Unidad Cisterna / Hidrante'), ('deposito', 'Depósito Central')], max_length=20, verbose_name='Unidad')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones generales')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('completado', models.DateTimeField(blank=True, null=True)),
                ('bombero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Bombero asignado')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_reporte', models.CharField(choices=[('Disponible', 'Disponible'), ('En Uso', 'En Uso'), ('No Disponible', 'No Disponible')], max_length=50, verbose_name='Estado reportado')),
                ('observacion', models.CharField(blank=True, default='', max_length=200, verbose_name='Observación')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.herramienta')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.parteguardia')),
            ],
        ),
    ]
