# Generated by Django 6.0.4 on 2026-08-06 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_parteguardia_partedetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del sitio')),
                ('localidad', models.CharField(blank=True, default='', max_length=100, verbose_name='Localidad')),
                ('dotacion', models.PositiveIntegerField(default=0, verbose_name='Dotación (bomberos activos)')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Móvil 1, Unidad 21, Unimog...', max_length=100, verbose_name='Denominación')),
                ('clasificacion', models.CharField(choices=[('primera_salida', 'Primera Salida / Estructural'), ('rescate_vehicular', 'Rescate Vehicular'), ('forestal', 'Incendio Forestal'), ('escalera', 'Escalera / Altura'), ('cisterna', 'Cisterna / Abastecimiento'), ('ambulancia', 'Ambulancia / Sanitario'), ('utilitario', 'Utilitario / Transporte'), ('especial', 'Equipo Especial')], max_length=30, verbose_name='Tipo / Función')),
                ('funcion', models.CharField(blank=True, default='', max_length=200, verbose_name='Función detallada')),
                ('modelo', models.CharField(blank=True, default='', max_length=100, verbose_name='Modelo / Marca')),
                ('capacidad_personal', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad de personal')),
                ('capacidad_agua', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad de agua (L)')),
                ('equipamiento', models.TextField(blank=True, default='', verbose_name='Equipamiento técnico')),
                ('estado_operativo', models.CharField(choices=[('base', 'En Base'), ('servicio', 'En Servicio'), ('ruta', 'En Ruta'), ('mantenimiento', 'En Mantenimiento')], default='base', max_length=20, verbose_name='Estado operativo')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='inventario.sitio', verbose_name='Sitio')),
            ],
            options={
                'ordering': ['sitio', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='herramienta',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas', to='inventario.unidadmovil', verbose_name='Unidad móvil'),
        ),
    ]
