services:
  db:
    image: postgres:15-alpine
    container_name: bomberos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=central_bomberos_db
      - POSTGRES_USER=admin_bombero
      - POSTGRES_PASSWORD=ClaveSegura123!
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: bomberos_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=central_bomberos_db
      - DB_USER=admin_bombero
      - DB_PASSWORD=ClaveSegura123!
      - DB_PORT=5432
      - JEFE_PASSWORD=jefepassword123
      - BOMBERO_PASSWORD=bomberopassword123
      - ADMIN_PASSWORD=admin123
      - SECRET_KEY=django-insecure-trabajo-final-bomberos
      - DEBUG=True
    depends_on:
      - db
    command: >
      sh -c "echo 'Esperando base de datos...' &&
             until python -c 'import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.connect((\"db\", 5432))' 2>/dev/null; do
               sleep 2
             done &&
             python manage.py migrate &&
             python manage.py poblar_cuartel &&
             python manage.py crear_cuentas &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
