from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_inventario, name='home'),
    path('panel/', views.panel_principal, name='panel_principal'),
    path('panel/bombero/', views.panel_bombero, name='panel_bombero'),
    path('unidades/', views.unidades_lista, name='unidades_lista'),
    path('unidades/agregar/', views.agregar_unidad, name='agregar_unidad'),
    path('unidades/editar/<int:id>/', views.editar_unidad, name='editar_unidad'),
    path('unidades/eliminar/<int:id>/', views.eliminar_unidad, name='eliminar_unidad'),
    path('configuracion/', views.configuracion, name='configuracion'),
    path('agregar/', views.agregar_herramienta, name='agregar_herramienta'),
    path('editar/<int:id>/', views.editar_herramienta, name='editar_herramienta'),
    path('eliminar/<int:id>/', views.eliminar_herramienta, name='eliminar_herramienta'),
    path('herramienta/<int:id>/nota/', views.agregar_nota, name='agregar_nota'),
    path('nota/<int:id>/eliminar/', views.eliminar_nota, name='eliminar_nota'),
    path('bombero/<int:id>/aprobar/', views.aprobar_bombero, name='aprobar_bombero'),
    path('evento/agregar/', views.agregar_evento, name='agregar_evento'),
    path('evento/<int:id>/eliminar/', views.eliminar_evento, name='eliminar_evento'),
    path('partes/', views.partes_guardia, name='partes_guardia'),
    path('partes/asignar/', views.asignar_parte, name='asignar_parte'),
    path('partes/<int:id>/completar/', views.completar_parte, name='completar_parte'),
    path('partes/<int:id>/ver/', views.ver_parte, name='ver_parte'),
    path('partes/<int:id>/eliminar/', views.eliminar_parte, name='eliminar_parte'),
    path('actividad/vaciar/', views.vaciar_actividad, name='vaciar_actividad'),
    path('exportar/csv/', views.exportar_inventario_csv, name='exportar_inventario_csv'),
    path('exportar/excel/', views.exportar_inventario_excel, name='exportar_inventario_excel'),
    path('reporte/', views.reporte_inventario, name='reporte_inventario'),
    path('reporte/pdf/', views.reporte_inventario_pdf, name='reporte_inventario_pdf'),
]