from django.urls import path
from .views import (
    home_inventario,
    agregar_herramienta,
    editar_herramienta,
    eliminar_herramienta,
    agregar_nota,
    eliminar_nota,
    aprobar_bombero,
    configuracion,
    agregar_evento,
    eliminar_evento,
    partes_guardia,
    asignar_parte,
    completar_parte,
    ver_parte,
    eliminar_parte,
    vaciar_actividad,
    panel_principal,
    panel_bombero,
    unidades_lista,
    agregar_unidad,
    editar_unidad,
    eliminar_unidad,
    exportar_inventario_csv,
    exportar_inventario_excel,
    reporte_inventario,
    reporte_inventario_pdf,
)

urlpatterns = [
    path('', home_inventario, name='home'),
    path('panel/', panel_principal, name='panel_principal'),
    path('panel/bombero/', panel_bombero, name='panel_bombero'),
    path('unidades/', unidades_lista, name='unidades_lista'),
    path('unidades/agregar/', agregar_unidad, name='agregar_unidad'),
    path('unidades/editar/<int:id>/', editar_unidad, name='editar_unidad'),
    path('unidades/eliminar/<int:id>/', eliminar_unidad, name='eliminar_unidad'),
    path('configuracion/', configuracion, name='configuracion'),
    path('agregar/', agregar_herramienta, name='agregar_herramienta'),
    path('editar/<int:id>/', editar_herramienta, name='editar_herramienta'),
    path('eliminar/<int:id>/', eliminar_herramienta, name='eliminar_herramienta'),
    path('herramienta/<int:id>/nota/', agregar_nota, name='agregar_nota'),
    path('nota/<int:id>/eliminar/', eliminar_nota, name='eliminar_nota'),
    path('bombero/<int:id>/aprobar/', aprobar_bombero, name='aprobar_bombero'),
    path('evento/agregar/', agregar_evento, name='agregar_evento'),
    path('evento/<int:id>/eliminar/', eliminar_evento, name='eliminar_evento'),
    path('partes/', partes_guardia, name='partes_guardia'),
    path('partes/asignar/', asignar_parte, name='asignar_parte'),
    path('partes/<int:id>/completar/', completar_parte, name='completar_parte'),
    path('partes/<int:id>/ver/', ver_parte, name='ver_parte'),
    path('partes/<int:id>/eliminar/', eliminar_parte, name='eliminar_parte'),
    path('actividad/vaciar/', vaciar_actividad, name='vaciar_actividad'),
    path('exportar/csv/', exportar_inventario_csv, name='exportar_inventario_csv'),
    path('exportar/excel/', exportar_inventario_excel, name='exportar_inventario_excel'),
    path('reporte/', reporte_inventario, name='reporte_inventario'),
    path('reporte/pdf/', reporte_inventario_pdf, name='reporte_inventario_pdf'),
]